name: Publish Docker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Login to GitHub Container Registry'
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u <vadimlipatov> --password-stdin          
      - uses: actions/checkout@main
      - name: Publish to registy
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/vadimlipatov/nest-top-app/nest-top-app 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "develop"