name: Publish Docker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: 'Login to GitHub Container Registry'
      - name: Checkout GitHub Action
      - uses: actions/checkout@main
      - name: Publish to registy
        uses: elgohr/Publish-Docker-Github-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}   
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/vadimlipatov/nest-top-app/nest-top-app 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "develop"